config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bugs, only: %i[index show]
      resources :projects, only: %i[index show]
    end
  end
  resources :webhooks, only: %i[create]

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :projects do
        resources :bugs, only: %i[new]
      end

      resources :users
      resources :bugs, except: %i[new] do
        collection do
          get :autocomplete
        end
      end
      resources :user_projects, except: %i[new update edit]

      namespace :developer do
        resources :bugs, only: %i[index new destroy]
      end

      resources :payment_intents, only: %i[create]
      resources :billing_portal, only: %i[create]
      resources :subscription_checkout, only: %i[index create destroy]


      get '/userprojects/viewprojects', to: 'user_projects#view_projects', as: :view_projects
      get '/project/bugs/:project_id', to: 'developer/bugs#project_bugs', as: :project_bugs
      post 'checkout/create', to: 'checkout#create'
    end


    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects
  has_many :bugs, inverse_of: :user, foreign_key: :qa_id, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 40, minimum: 2 }
  validates :user_type, presence: true

  enum user_type: { manager: 0, developer: 1, qa: 2 }
  after_initialize :set_default_user_type, if: :new_record?

  alias_method :authenticate, :valid_password?

  def self.from_token_payload(payload)
    self.find payload["sub"]
  end

  def set_default_user_type
    self.user_type ||= :user
  end

  after_create do
    customer= Stripe::Customer.create(email: self.email)
    update(stripe_customer_id: customer.id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @userprojects = User.find(params[:id]).projects
    authorize @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<h1 class="m-3">Manager's Panel</h1>
<div class="container m-5">
  <div class="row">
    <div class="col-lg-3">
      <%= render 'home/userpfp' %>
    </div>
    <div class="col-lg-9">
        <h4>Users List</h4>
        <table class="table table-hover table-striped table-bordered">
          <thead >
            <tr class="table-dark">
              <th scope="col">User ID</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">User Type</th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <% if (user.manager?) %>
            <% else %>
              <tbody>
                <tr>
                  <th scope="row"><%= user.id%></th>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.user_type.capitalize %></td>
                  <td><%= link_to "Show ", user_path(user), class:"btn btn-primary" %></td>
                  <td><%= link_to "Remove Projects", user_projects_path(user_id: user.id), class:"btn btn-danger" %></td>
                  <td><%= link_to "Assign Projects", user_project_path(user.id), class:"btn btn-success" %></td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
        </table>
        <p class="lead">
          <%= link_to "Show Projects", projects_path, class:"btn btn-primary btn-lg" %>
          <%= link_to "Create A Project", new_project_path, class:"btn btn-warning btn-lg" %>
        </p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron-index m-5 mt-0">
  <div class="jumbotron ">
    <h4>UserID: <%= @user.id %> </h4>
    <h4>Username: <%= @user.name %> </h4>
    <h4>Email: <%= @user.email%> </h4>
    <h4>Type: <%= @user.user_type.capitalize %> </h4>
    <br>
    <h4>Assigned Projects: </h4>
    <% @userprojects.each do |userproject| %>
        <i>ProjectID: <%= userproject.id %> , Project Name: <%= userproject.name %></i>
        <br>
    <% end %>
    <br>
    <br>
  </div>
</div>
  <br>
  <br>
  <%= link_to "Back To Home", authenticated_root_path, class:"btn btn-primary btn-lg" %>