config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bugs, only: %i[index show]
      resources :projects, only: %i[index show]
    end
  end
  resources :webhooks, only: %i[create]

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :projects do
        resources :bugs, only: %i[new]
      end

      resources :users
      resources :bugs, except: %i[new] do
        collection do
          get :autocomplete
        end
      end
      resources :user_projects, except: %i[new update edit]

      namespace :developer do
        resources :bugs, only: %i[index new destroy]
      end

      resources :payment_intents, only: %i[create]
      resources :billing_portal, only: %i[create]
      resources :subscription_checkout, only: %i[index create destroy]


      get '/userprojects/viewprojects', to: 'user_projects#view_projects', as: :view_projects
      get '/project/bugs/:project_id', to: 'developer/bugs#project_bugs', as: :project_bugs
      post 'checkout/create', to: 'checkout#create'
    end


    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/user_project.rb
# frozen_string_literal: true

class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project

  scope :user_search, -> (current_user){ where(user_id: current_user).pluck(:project_id)}
end

app/controllers/user_projects_controller.rb
# frozen_string_literal: true

class UserProjectsController < ApplicationController
  def index
    @projects = User.find(params[:user_id]).projects
    @user = User.find(params[:user_id])
    authorize @user
  end

  def show
    project = UserProject.where('user_id = ?', params[:id]).pluck('project_id')
    @user = User.find(params[:id])
    authorize @user, policy_class: UserProjectPolicy
    @userprojects = Project.where.not(id: project).where(user_id: current_user.id)
    render 'unassigned'
  end

  def create
    @userproject = UserProject.new(user_project_params)
    authorize @userproject

    if @userproject.save
      flash[:success] = 'Project was successfully Assigned.'
    else
      flash[:error] = @bug.errors.full_messages.to_sentence
    end
    redirect_to action: 'show', id: params[:user_id]
  end

  def destroy
    @project = UserProject.where(user_id: params[:user_id], project_id: params[:id]).take
    authorize @project
    flash[:success] = 'Project was successfully unassigned.' if UserProject.destroy(@project.id)
    redirect_to action: 'index', user_id: params[:user_id]
  end

  def view_projects
    authorize UserProject
    @projects = UserProject.where(user_id: current_user.id)

    render 'view_projects'
  end

  def user_project_params
    params.permit(:user_id, :project_id, :name, :manager_id)
  end
end

app/helpers/user_projects_helper.rb
# frozen_string_literal: true

module UserProjectsHelper
  def panel_heading(user)
    user.developer? ? "Developer's Panel" : "QA's Panel"
  end
end

app/views/user_projects/_columns.html.erb
<th scope="row"><%= current_user.developer? ? project.project_id : project.id %></th>
<td><%= project.name %></td>
<td><%= project.user_id %></td>
<td><%= project.created_at %></td>
<td><%= project.updated_at %></td>

app/views/user_projects/_headings.html.erb
<th scope="col">Project ID</th>
<th scope="col">Name</th>
<th scope="col">Manager ID</th>
<th scope="col">Created At</th>
<th scope="col">Updated At</th>
<th scope="col"></th>
<th scope="col"></th>

app/views/user_projects/_table.html.erb
<% @projects.each do |project| %>
    <tbody>
      <tr>
        <%= render "user_projects/columns", project: project %>
        <% if current_user.developer? %>
          <td><%= link_to "Unassigned Bugs", project_code_piece_users_path(project.project_id), class:"btn btn-warning" %></td>
          <td><%= link_to "Assigned Bugs", code_piece_user_path(project.project_id), class:"btn btn-success" %></td>
        <% elsif current_user.qa? %>
          <td><%= link_to "Create A Bug", new_project_bug_url(project.project_id), class:"btn btn-warning" %></td>
          <td><%= link_to "Create A Feature", new_project_feature_url(project.project_id), class:"btn btn-primary" %></td>
        <% elsif current_user.manager? %>
          <td><%= link_to "Show ", project, class:"btn btn-warning" %></td>
          <td><%= link_to "Edit ", edit_project_url(project.id), class:"btn btn-primary" %></td>
          <td><%= button_to "Destroy ", project, method: :delete, class:"btn btn-danger" %></td>
        <% end %>
      </tr>
    </tbody>
<% end %>

app/views/user_projects/index.html.erb
<h1 class='m-3'><%= @user.name %>'s Assigned Projects</h1>
<div class="m-3">
  <table class="table table-hover table-striped table-bordered">
    <thead >
      <tr class="table-dark">
        <%= render "headings"%>
      </tr>
    </thead>
    <% @projects.each do |project| %>
      <tbody>
        <tr>
        <%= render "columns", project: project %>
          <% if project.user_id == current_user.id%>
            <td><%= link_to "Show ", project, class:"btn btn-primary" %></td>
            <td><%= link_to "Remove Project ", user_project_url(project.id,user_id: @user.id,), class:"btn btn-danger", method: :delete %></td>
          <% else %>
            <td><button class="btn btn-primary disabled"> Show</button></td>
            <td><button class="btn btn-danger disabled"> Remove Project</button></td>
          <% end %>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= link_to "Unassigned Projects", user_project_path(@user.id), class:"btn btn-dark" %>
  <br/>
  <br/>
  <%= link_to "Back To Users", users_path, class:"btn btn-primary" %>
</div>

app/views/user_projects/unassigned.html.erb
<h1 class='m-3'><%= @user.name %>'s Unassigned Projects </h1>

<div class="m-3">
  <table class="table table-hover table-striped table-bordered">
    <thead >
      <tr class="table-dark">
        <%= render "headings"%>
      </tr>
    </thead>
    <% @userprojects.each do |userproject| %>
      <tbody>
        <tr>
          <%= render "columns", project: userproject %>
          <td><%= link_to "Show ", userproject, class:"btn btn-primary" %></td>
          <td><%= link_to "Assign ", user_projects_url(user_id: @user.id, project_id: userproject.id, name: userproject.name, manager_id: userproject.user_id), class:"btn btn-success", method: :post %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= link_to "Assigned Projects ", user_projects_path(user_id: @user.id), class:"btn btn-dark" %>
  <br/>
  <br/>
  <%= link_to "Back To Home", users_path, class:"btn btn-primary" %>
</div>

app/views/user_projects/view_projects.html.erb
<%= render 'layouts/messages' %>
<h1><%= panel_heading(current_user) %> </h1>
<div class="container" >
  <div class="row">
    <div class='col-lg-3'>
      <%= render "home/userpfp" %>
    </div>
    <div class='col-lg-9'>
      <h1 class='m-3'>Assigned Projects </h1>
      <div class="m-3">
        <table class="table table-hover table-striped table-bordered">
          <thead >
            <tr class="table-dark">
              <%= render "headings" %>
            </tr>
          </thead>
          <% @projects.each do |project| %>
            <tbody>
              <tr>
                <th scope="row"><%= project.project_id %></th>
                <td><%= project.name %></td>
                <td><%= project.manager_id %></td>
                <td><%= project.created_at %></td>
                <td><%= project.updated_at %></td>
              <% if current_user.developer? %>
                <td><%= link_to "Assign Bugs", project_bugs_path(project.project_id, status: "unassigned"), class:"btn btn-success" %></td>
                <td><%= link_to "Remove Bugs", project_bugs_path(project.project_id, status: "assigned"), class:"btn btn-danger" %></td>
              <% elsif current_user.qa? %>
                <td><%= link_to "Create A Bug", new_project_bug_url(project.project_id), class:"btn btn-warning" %></td>
              <% end %>
              </tr>
            </tbody>
          <% end %>
        </table>
        <p class="lead">
            <% if current_user.qa? %>
              <%= link_to "All Bugs", bugs_path(status: "all"), class:"btn btn-dark" %>
              <%= link_to "My Bugs", bugs_path(status: "assigned"), class:"btn btn-success" %>
              <%= link_to "All Projects", projects_url, class:"btn btn-primary" %>
              <%= link_to "Subscription", subscription_checkout_index_path, class:"btn btn-warning" %>
            <% else %>
              <%= link_to "All Bugs", developer_bugs_path(status: "all"), class:"btn btn-dark" %>
              <%= link_to "My Bugs", developer_bugs_path(status: "assigned"), class:"btn btn-success" %>
            <% end %>
        </p>

      </div>
    </div>
  </div>
</div>