config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bugs, only: %i[index show]
      resources :projects, only: %i[index show]
    end
  end
  resources :webhooks, only: %i[create]

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :projects do
        resources :bugs, only: %i[new]
      end

      resources :users
      resources :bugs, except: %i[new] do
        collection do
          get :autocomplete
        end
      end
      resources :user_projects, except: %i[new update edit]

      namespace :developer do
        resources :bugs, only: %i[index new destroy]
      end

      resources :payment_intents, only: %i[create]
      resources :billing_portal, only: %i[create]
      resources :subscription_checkout, only: %i[index create destroy]


      get '/userprojects/viewprojects', to: 'user_projects#view_projects', as: :view_projects
      get '/project/bugs/:project_id', to: 'developer/bugs#project_bugs', as: :project_bugs
      post 'checkout/create', to: 'checkout#create'
    end


    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :bugs, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { maximum: 40, minimum: 5 }

  searchkick text_middle: [:name]

  def search_data
    {
      name: name
    }
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProjectsController < ApplicationController
      before_action :authenticate_user

      def index
        projects = Project.all
        projects = params[:query].present? ? Project.search(params[:query],{fields: ['name'], match: :text_middle}) : Project.all
        render json: projects
      end

      def show

        project = Project.find_by(id: params[:id])
        if(project.nil?)
          record_not_found;
        else
          render json: project
        end

      end

      private
      def record_not_found
        render status: :not_found, json: {message: "Not found"}
      end

    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
    authorize @projects
  end

  def show
    @userprojects = Project.find(params[:id]).users
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), flash: { success: 'Project was successfully created.' } }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @project

    respond_to do |format|
      if @project.update(project_params)

        format.html { redirect_to project_url(@project), flash: { success: 'Project was successfully updated.' } }
      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  def destroy
    authorize @project
    if @project.destroy
      flash[:success] = 'Project was successfully destroyed.'
    else
      flash[:error] = @project.errors.full_messages.to_sentence
    end
    redirect_to projects_url(@project)
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :id).merge(user_id: current_user.id)
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true, :validate => true ) do |form| %>
  <div class="form-group mb-2">
    <% form.label :name, style: "display: block"  %>
    <%= form.text_field :name, class:"form-control", placeholder:"Project Name" %>
  </div>
  <div>
  <br>
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing a Project</h1>
<br>
<%= render "form", project: @project %>
<br>
<div>
  <%= link_to "Show ", @project, class:"btn btn-secondary" %>
  <%= link_to "Back ", projects_path, class:"btn btn-dark" %>
</div>

app/views/projects/index.html.erb
<div class="m-3">
  <table class="table table-hover table-striped table-bordered">
    <thead >
      <tr class="table-dark">
        <%= render "user_projects/headings" %>
        <th scope="col"></th>
      </tr>
    </thead>
    <% @projects.each do |project| %>
      <tbody>
        <tr>
          <%= render "user_projects/columns" , project: project %>
          <% if current_user.manager? && current_user.id == project.user_id %>
            <td><%= link_to "Show ", project, class:"btn btn-warning" %></td>
            <td><%= link_to "Edit ", edit_project_url(project.id), class:"btn btn-primary" %></td>
            <td><%= button_to "Destroy ", project, method: :delete, class:"btn btn-danger" %></td>
          <% else %>
            <td><button class="btn btn-warning disabled"> Show</button></td>
            <td><button class="btn btn-primary disabled"> Edit</button></td>
            <td><button class="btn btn-danger disabled"> Destroy</button></td>
          <% end %>
        </tr>
      </tbody>
    <% end %>
  </table>
  <% if current_user.manager? %>
    <%= link_to "New Project", new_project_path, class:'btn btn-secondary'%>
  <% end %>
  <%= link_to "Back To Home", authenticated_root_path, class:'btn btn-primary'%>
</div>

app/views/projects/new.html.erb
<h1>Create A Project</h1>
<br>
<%= render "form", project: @project %>
<br>
<div>
  <%= link_to "Back to Home", authenticated_root_path, class:"btn btn-primary" %>
</div>

app/views/projects/show.html.erb
<div class="jumbotron-index m-5 mt-0">
  <div class="jumbotron ">
    <h3><%= @project.name %> </h3>
   <h3>Manager ID: <%= @project.user_id %> </h3>
    <br>
    <h4>Assigned Users: </h4>
    <% @userprojects.each do |userproject| %>
        <i>UserID: <%= userproject.id %> , Username: <%= userproject.name %></i>
        <br>
    <% end %>
    <br>
    <br>
    <p class="lead">
      <%= link_to "Edit", edit_project_path(@project), class:"btn btn-secondary" %>
      <%= link_to "Show Project List", projects_path, class:"btn btn-dark" %>
    </p>
  </div>
</div>
<%= button_to "Destroy this project", @project, class:"btn btn-danger btn-md", method: :delete %>
<br>
<br>
<%= link_to "Back To Home", authenticated_root_path, class:"btn btn-primary btn-lg" %>
<br>
<br>
<button class="btn btn-dark mt-5" onclick="history.back()">Go Back</button>