config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bugs, only: %i[index show]
      resources :projects, only: %i[index show]
    end
  end
  resources :webhooks, only: %i[create]

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :projects do
        resources :bugs, only: %i[new]
      end

      resources :users
      resources :bugs, except: %i[new] do
        collection do
          get :autocomplete
        end
      end
      resources :user_projects, except: %i[new update edit]

      namespace :developer do
        resources :bugs, only: %i[index new destroy]
      end

      resources :payment_intents, only: %i[create]
      resources :billing_portal, only: %i[create]
      resources :subscription_checkout, only: %i[index create destroy]


      get '/userprojects/viewprojects', to: 'user_projects#view_projects', as: :view_projects
      get '/project/bugs/:project_id', to: 'developer/bugs#project_bugs', as: :project_bugs
      post 'checkout/create', to: 'checkout#create'
    end


    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/bug_users/assigned.html.erb
<h1 class="m-3"><%= current_user.name %>'s Assigned Bugs </h1>
<div class="m-3">
  <table class="table table-hover table-striped table-bordered">
    <thead >
      <tr class="table-dark">
        <%= render "bugs/headings"%>
        <th scope="col"></th>
      </tr>
    </thead>
    <% @bugs.each do |bug| %>
      <tbody>
        <tr>
          <%= render "bugs/columns", bug: bug %>
          <td><%= link_to "Show ", bug_path(bug.id), class:"btn btn-warning" %></td>
          <td><%= link_to "Remove", bug_path(bug.id), class:"btn btn-danger", method: :delete %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= link_to "Back To Projects", view_projects_path(current_user.id), class:"btn btn-success" %>
</div>